### PR TITLE
PR for the SeatMap feature.

### LINKED ISSUE #62: add support for Seatmap Display API
https://developers.amadeus.com/self-service/category/air/api-doc/seatmap-display/api-reference

### PR DESCRIPTION
**Pull request by johandavidsen**
Fixes #62 

## Changes for this pull request
Implemented the SeatMap API GET and POST requests.

## Checklist

* Ensure all tests pass and linting
* Ensure this PR only changes what it is intended to change

### CODE REVIEW

**Review by xianqiliu — APPROVED** [review]

**Comment by johandavidsen** [comment]
I consider this to be feature complete. Please let me know, if anything is missing?

**Comment by xianqiliu** [comment]
> I consider this to be feature complete. Please let me know, if anything is missing?

@tsolakoua @minjikarin Hey guys, this PR looks good to me. Please do a double review and go ahead with this PR. :/

**Comment by tsolakoua** [comment]
Thanks for your contribution @johandavidsen  and for your review @xianqiliu :) It looks like the build for PHP 8.1 still fails so I am not able to merge the PR it yet.

**Comment by xianqiliu** [comment]
@johandavidsen hey, as for that failure for [building on GitHub actions](https://github.com/amadeus4dev-examples/amadeus-php/actions/runs/3743285674/jobs/6363895324), I suggest you follow the [contributor guide](https://github.com/amadeus4dev-examples/amadeus-php/blob/master/.github/CONTRIBUTING.md) and you will see we need to run the following commands to fix the code style, I believe it would perfectly solve this failure. 
```
vendor/bin/php-cs-fixed fix src 
vendor/bin/php-cs-fixed fix tests
```

**Comment by johandavidsen** [comment]
The CS should be fixed now.

**Pull request merged**
